version: '3'
services:
  web:
    build: site
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: foliomakerroot
      MYSQL_DATABASE: foliomakerdb
      MYSQL_USER: foliomakeruser
      MYSQL_PASSWORD: foliomakerpsw
    ports:
      - "3306:3306"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
