version: '3'
services:
  web:
    build: site
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
    # networks:
    #   - pg_network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: ${DB_ROOT_USER}
      POSTGRES_DATABASE: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    # networks:
    #   - pg_network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PG_LISTEN_PORT}
    ports:
      - "5050:80"
#     networks:
#       - pg_network
#     depends_on:
#       - db

# networks:
#   pg_network:
#     driver: bridge
