/:
  controller: Main
  action: home

/dashboard:
  controller: Main
  action: dashboard

/editor:
  controller: Main
  action: editor

/a-propos:
  controller: Main
  action: aboutUs

/components:
  controller: Main
  action: components

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/installer_site:
  controller: Installer
  action: setup_site

/user/create:
  controller: User
  action: create

/user/edit:
  controller: User
  action: update

/user/editlist:
  controller: User
  action: updateList

/user/updateList:
  controller: User
  action: updateList

/user/delete:
  controller: User
  action: delete

/user/deletelist:
  controller: User
  action: deleteList

/user/list:
    controller: User
    action: list

/menu/create:
  controller: Menu
  action: showAdd

/menu/list:
  controller: Menu
  action: list

/menu/edit/{id}:
  controller: Menu
  action: showEdit

/menu/update/{id}:
  controller: Menu
  action: update

/menu/delete:
  controller: Menu
  action: delete

/verify_email:
  controller: Security
  action: verifyEmail

