/:
  controller: Main
  action: home

/a-propos:
  controller: Main
  action: aboutUs

/components:
  controller: Main
  action: components

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/installer_site:
  controller: Installer
  action: setup_site

/user/edit:
  controller: User
  action: update

/user/delete:
  controller: User
  action: delete

