/:
  controller: Main
  action: home

/dashboard:
  controller: Main
  action: dashboard

/editor:
  controller: Main
  action: editor

/a-propos:
  controller: Main
  action: aboutUs

/components:
  controller: Main
  action: components

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/installer_site:
  controller: Installer
  action: setup_site

/dashboard/pages:
  controller: Dashboard
  action: pages

/dashboard/create-page:
  controller: Page
  action: createPage

/{path}:
  controller: Page
  action: viewPage
